# Compose file which uses a test build of the API
# Use this for CI/CD maybe? May need to modify
# Before you start with CI/CD, coordinate with EVERYONE on this

services:

    # API container
    api:

        # Build from Dockerfile in this scope
        build:
            context: .
            dockerfile: Dockerfile.test

        # Don't run tests until db is up
        command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; pytest'

        # For docker compose, we'll manually override the env variables
        environment:
            - POSTGRES_HOST=db:5432
            - POSTGRES_DB=postgres_test
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - USE_SSL=false
            - AZURE_STORAGE_CONNECTION_STRING=""
            - AZURE_STORAGE_CONTAINER_NAME=""
            - USE_AZURE_BLOB=false

        # Map ports
        ports:
            - 8000:8000

        # Requires db container dependency
        depends_on:
            - db
            
    # DB container running postgres
    db:

        # Use official postgres 14.6 image
        image: postgres:14.6

        # Map ports
        ports:
            - 5432:5432

        # Must define these
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=postgres_test